<?php return array (
    'debug' => true,
    'appName' => 'Borealis',
    'appVersion' => '1.2.0',
    'appDescription' => '',
    'appAuthor' => 'Oliver Earl',
    'appAuthorEmail' => 'ole4@aber.ac.uk',
    'maxElements' => 4,
    'hostname' => 'db.dcs.aber.ac.uk',
    'dbName' => 'ole4',
    'username' => 'ole4',
    'password' => '***REMOVED***',
    'dbType' => 'mysql',
    'magnetometer_hostname' => 'imapspc0017.imaps.aber.ac.uk',
    'magnetometer_username' => 'imaps\ole4',
    'magnetometer_password' => '***REMOVED***',
    'magnetometer_share' => 'magdata',
    'magnetometer_latest' => '111',
);
