<?php return array (
  'debug' => true,
  'appName' => 'Borealis',
  'appVersion' => '1.4.0',
  'appDescription' => 'Data collation and graphing tool with API for magnetometer data.',
  'appAuthor' => 'Oliver Earl',
  'appAuthorEmail' => 'ole4@aber.ac.uk',
  'maxElements' => 4,
  'hostname' => 'fillme',
  'dbName' => 'fillme',
  'username' => 'fillme',
  'password' => 'fillme',
  'dbType' => 'mysql',
  'magnetometer_hostname' => 'imapspc0017.imaps.aber.ac.uk',
  'magnetometer_username' => 'imaps\usernamehere',
  'magnetometer_password' => '',
  'magnetometer_share' => 'magdata',
  'magnetometer_latest' => '001',
);
