<div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
            <ul class="nav flex-column">
                <!-- TODO: Find a fix for this, can I remove it? -->
                <li class="nav-item">
                    <a class="nav-link active" href="#">
                        Dashboard <span class="sr-only">(current)</span>
                    </a>
                </li>
                <!-- END -->
                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span><?= $app->getLocaleString('magnetometer'); ?></span>
                    <a class="d-flex align-items-center text-muted" href="#">
                    </a>
                </h6>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?graph=latest">
                        <?= $app->getLocaleString('magnetometer.latestEntry'); ?>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?graph=all">
                        <?= $app->getLocaleString('magnetometer.displayAll'); ?>
                    </a>
                </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span><?= $app->getLocaleString('radio.data'); ?></span>
                <a class="d-flex align-items-center text-muted" href="#">
                </a>
            </h6>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <em><?= $app->getLocaleString('unimplemented'); ?></em>
                    </a>
                </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span><?= $app->getLocaleString('esa.data'); ?></span>
                <a class="d-flex align-items-center text-muted" href="#">
                </a>
            </h6>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <em><?= $app->getLocaleString('unimplemented'); ?></em>
                    </a>
                </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span><?= $app->getLocaleString('application'); ?></span>
                <a class="d-flex align-items-center text-muted" href="#">
                </a>
            </h6>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="index.php?p=about">
                        <?= $app->getLocaleString('app.about'); ?>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?p=settings">
                        <?= $app->getLocaleString('app.settings'); ?>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>
