<?php
/**
 * Created by PhpStorm.
 * User: oliver
 * Date: 20/03/2018
 * Time: 23:19
 */
?>
<!-- Graph Scripts -->
<?php if (isset($graphOn)): ?>
<?php
$tempArray = [];
foreach ($entries as $entry) {
    array_push($tempArray, $entry['value']);
}
?>
<script>
    var ctx = document.getElementById("chart");
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            datasets: [{
                data: [<?= implode(',', $tempArray); ?>],
                lineTension: 0,
                backgroundColor: 'transparent',
                borderColor: '#007bff',
                borderWidth: 4,
                pointBackgroundColor: '#007bff'
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            },
            legend: {
                display: false,
            }
        }
    });
</script>
<?php endif; ?>
