<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="index.php"><?= $app->getAppName(); ?> <small><?= $app->getConfigEntry('appVersion'); ?></small></a>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <?= ($app->getLanguage() === 'en'
                ? '<a class="nav-link" href="index.php?language=cy">' . "{$app->getLocaleString('welsh')}</a>"
                : '<a class="nav-link" href="index.php?language=en">' . "{$app->getLocaleString('english')}</a>"); ?>
        </li>
    </ul>
</nav>
