<div class="row">
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2"><?= $app->getLocaleString('home.title'); ?></h1>
        </div>
        <h2><?= $app->getLocaleString('home.subtitle'); ?></h2>
        <p><?= $app->getLocaleString('home.introduction'); ?></p>
    </main>
</div>
