<div class="row">
    <!-- TODO: Total refactor -->
    <table class="table table-responsive">
        <thead>
        <tr>
            <th>Graphical View</th>
            <th>Date Recorded</th>
            <th>Magnetometer Value</th>
            <th>Instrument Temperature</th>
            <th>Unix Timestamp</th>
            <th>labVIEW Timestamp</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($entriesToRetrieve as $entry): ?>
            <tr>
                <?php // TODO Fix ID implementation "index.php?graph={$entry['id']}" ?>
                <td><a class="btn btn-primary align-content-center" href="">View</a></td>
                <td><?= date($entry.getTimestamp()); ?></td>
                <td><?= $entry.getValue(); ?></td>
                <td><?= $entry.getTemp(); ?></td>
                <td><?= strtotime($entry.getTimestamp()); ?></td>
                <td><?= (strtotime($entry.getTimestamp()) + 2082844800); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
